# ~/.config/scooter/config.toml

[editor_open]
command = "nvim +%line %file"
exit = true

[preview]
syntax_highlighting = true
syntax_highlighting_theme = "Catppuccin Mocha"
wrap_text = false

[style]
true_color = true

[search]
disable_prepopulated_fields = false
